version: '3.8'

services:
  app:
    container_name: front
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
  nginx:
    container_name: nginx
    image: nginx:latest  # Zamiast build, używamy bezpośrednio najnowszego obrazu
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    #command: ["wait-for-it", "app:5173", "--", "nginx", "-g", "daemon off;"]
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl/server.crt:/etc/ssl/certs/server.crt
      - ./docker/ssl/server.key:/etc/ssl/certs/server.key
    restart: always
